payout/rester

- Gemfile.lock
- lib/rester.rb
- lib/rester/client.rb
- lib/rester/client/adapters.rb
- lib/rester/client/adapters/local_adapter.rb
- lib/rester/middleware/error_handling.rb
- lib/rester/service/object.rb
- spec/rester/client/adapters/local_adapter_spec.rb
- spec/rester/client_spec.rb
- spec/rester_spec.rb
> Adding LocalAdapter

- Gemfile.lock
- README.md
- lib/rester/service.rb
- lib/rester/service/object.rb
- spec/dummy/dummy_service.rb
- spec/rester/client/adapters/local_adapter_spec.rb
- spec/rester/client_spec.rb
#13 - Treat id as any other parameter
#14 - Make search and create instance methods.
> [#13,#14] Passing id as param, search/create to instance methods

- lib/rester/client.rb
- lib/rester/client/response.rb
- lib/rester/middleware/error_handling.rb
- lib/rester/utils.rb
- spec/rester/client/response_spec.rb
- spec/rester/client_spec.rb
- spec/rester/rspec_spec.rb
- spec/rester/service_spec.rb
- spec/stubs/dummy_service_stub.yml
> [#31] Make client return with a response object

- lib/rester/client/adapters/stub_adapter.rb
- spec/rester/client/adapters/stub_adapter_spec.rb
- spec/rester/client_spec.rb
> [#43] Fix bug with request param validation

- lib/rester/errors.rb
- lib/rester/middleware/error_handling.rb
- lib/rester/service/resource.rb
- spec/dummy/dummy_service.rb
- spec/rester/client_spec.rb
- spec/rester/rspec_spec.rb
- spec/stubs/dummy_service_stub.yml
> [#49] Implementing new error! interface.

- lib/rester/client/adapters/stub_adapter.rb
- lib/rester/rspec.rb
- lib/rester/utils.rb
- lib/rester/utils/stub_file.rb
- spec/rester/client/adapters/stub_adapter_spec.rb
- spec/stubs/dummy_service_stub.yml
- spec/stubs/dummy_stub.yml
#42
Thoughts, @kayvonghaffari?
> Alternative implementation of #42

- Gemfile.lock
- lib/rester/client/response.rb
- spec/rester/client/response_spec.rb
> [#58] Add respond_to_missing? to Response

- lib/rester/client/adapters/stub_adapter.rb
- lib/rester/utils.rb
- lib/rester/utils/stub_file.rb
- spec/rester/utils_spec.rb
> Converting `nil` to 'null' in stub request hashes

- lib/rester/rspec.rb
- lib/rester/utils.rb
- lib/rester/utils/rspec.rb
- spec/dummy/dummy_service.rb
- spec/rester/rspec_spec.rb
- spec/rester/utils/rspec_utils_spec.rb
- spec/stubs/dummy_service_stub.yml
> Add custom matcher for RSpec contract testing

- README.md
- lib/rester.rb
- lib/rester/client.rb
- lib/rester/client/adapters.rb
- lib/rester/client/adapters/adapter.rb
- lib/rester/client/adapters/http_adapter.rb
- lib/rester/client/adapters/http_adapter/connection.rb
- lib/rester/client/adapters/local_adapter.rb
- lib/rester/client/adapters/stub_adapter.rb
- lib/rester/errors.rb
- lib/rester/utils.rb
- lib/rester/utils/circuit_breaker.rb
- spec/dummy/dummy_service.rb
- spec/rester/client/adapters/http_adapter_spec.rb
- spec/rester/client/adapters/local_adapter_spec.rb
- spec/rester/client/adapters_spec.rb
- spec/rester/client_spec.rb
- spec/rester/utils/circuit_breaker_spec.rb
- spec/rester_spec.rb
> Implementing timeouts and circuit breaker

- lib/rester/service/resource/params.rb
- spec/rester/service/resource/params_spec.rb
> Adding pre-parse match validation.

- lib/rester/client/adapters/stub_adapter.rb
- spec/rester/client/adapters/stub_adapter_spec.rb
> [#60] Improve error message for mismatched request params

- lib/rester/service/resource/params.rb
- spec/rester/service/resource/params_spec.rb
> [#77] Add more validation for Array / Hash params

- lib/rester/rspec.rb
> [#72] Make undefined producer side tests pending

- README.md
- lib/rester/client.rb
- spec/rester/client_spec.rb
- spec/rester_spec.rb
> [#80] Add option to enable/disable circuit breaker manually

- lib/rester/client.rb
- lib/rester/service/middleware/request_handler.rb
- spec/rester/client_spec.rb
- spec/rester/service/middleware/request_handler_spec.rb
> Logging response time in client and service

- lib/rester.rb
- lib/rester/client.rb
- lib/rester/client/middleware/request_handler.rb
- lib/rester/service/middleware/request_handler.rb
- spec/rester/client_spec.rb
- spec/rester/service/middleware/error_handling_spec.rb
- spec/rester/utils/logger_wrapper_spec.rb
- spec/rester_spec.rb
> Adding Rester.wrap_request

- .travis.yml
- lib/rester.rb
- lib/rester/service.rb
- spec/dummy/config/initializers/rester.rb
- spec/rester/service_spec.rb
- spec/rester_spec.rb
#90
I also added support for anonymous services (i.e., `Class.new(Rester::Service)`), which was helpful in this case for testing.
> Installing client middleware on first connect.

- lib/rester/service/resource/params.rb
- spec/rester/service/resource/params_spec.rb
> [#95] Allow for dynamic param fields using regex

- lib/rester/client/adapters.rb
- spec/rester_spec.rb
> [#98] Improve error message for adapters::connect

- lib/rester.rb
> [#100] Check if Rails responds to application
